spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/sach_api
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      static-locations: file:upload/
  mvc:
    static-path-pattern: /upload/**
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

server:
  tomcat:
    basedir: /Users/admin/Desktop/SachAPI


application:
  upload-dir: /upload
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      access-token:
        expiration: 1000000
      refresh-token:
        expiration: 604800000
