spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
      types:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_api
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      static-locations: file:upload/
  mvc:
    static-path-pattern: /upload/**
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 911301206062-h9uf3us1dokhn1d0j2ve26ddbq82er3c.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - profile
              - email
          github:
            client-id: bb681f71fe55500bad13
            client-secret: f1654c461ccf155964d016fdb1495c3fd8cb618d
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

server:
  tomcat:
    basedir: /Users/admin/Desktop/ecommerce-api

application:
  upload-dir: /upload
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      access-token:
        expiration: 30000
      refresh-token:
        expiration: 604800000
  vnpay:
    secret-key: MDYQDGGNRJCKVYSGMDMNXLXYPTPCYJPR
    terminal-id: WAA4ZVYD
logging:
  level:
    org.springframework.security: DEBUG

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
    swagger-ui:
      path: /api-docs/swagger-ui.html
